### ISSUE TITLE
Can't find the namespace 'LightBuzz.Vitruvius.FingerTracking'

### ISSUE THREAD

**Issue by Cheryl115** [LightBuzz/Kinect-Finger-Tracking#2]
Hi, I'm trying to compile the code with my project, but I can't use the namespace 'LightBuzz.Vitruvius.FingerTracking', how can I get this namespace, please help me!

**Comment by Vangos** [comment]
You need to import the class library into your project. If you are new to C# and Visual Studio, clone the project, open the KinectFingerTracking.sln file and build on top of the KinectFingerTracking project.
